spring.application.name=AIProjectSB5

# PostgreSQL Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sb5_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# H2 Console (for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# GigaChat (Main LLM)
#gigachat.auth.key=${GIGACHAT_AUTH_KEY}
gigachat.model=GigaChat-Pro

server.port=8088

general.llm.default=CLOUD_GIGA_CHAT_2

# Cloud.ru (Secondary LLM)
cloudru.base.url=https://foundation-models.api.cloud.ru/v1/chat/completions
cloudru.authorization.key=

# GigaChat endpoints
gigachat.base.url=https://gigachat.devices.sberbank.ru/api/v1/chat/completions
gigachat.auth.url=https://ngw.devices.sberbank.ru:9443/api/v2/oauth
gigachat.authorization.key=

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.type.preferred_array_jdbc_type=ARRAY